import { Platform, StyleSheet } from 'react-native'

export const COLORS = {
  bg: '#f3f4f6',
  sidebarBg: '#f9fafb',
  text: '#111827',
  muted: '#6b7280',
  border: '#d1d5db',
  white: '#ffffff',
  primary: '#2563eb',
  primarySoft: '#eff6ff',
  danger: '#dc2626',
}

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },

  header: {
    height: 56,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web'
      ? ({ position: 'sticky', top: 0, zIndex: 10 } as any)
      : null),
  },
  headerLogo: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '900',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 200,
    justifyContent: 'flex-end',
  },
  headerUser: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 280,
  },
  logoutBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  logoutText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  // Dashboard layout
  dashboardRoot: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: COLORS.bg,
  },
  sidebar: {
    width: 280,
    backgroundColor: COLORS.sidebarBg,
    borderRightWidth: 1,
    borderRightColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  sidebarTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  sidebarGroupTitle: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 6,
    marginBottom: -2,
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginTop: 12,
    marginBottom: 12,
  },
  sidebarList: {
    flex: 1,
  },
  sidebarListContent: {
    gap: 8,
    paddingBottom: 16,
  },
  sidebarItem: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.sidebarBg,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  sidebarItemActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primarySoft,
  },
  sidebarItemText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '700',
  },
  sidebarItemTextActive: {
    fontWeight: '900',
    color: COLORS.primary,
  },
  main: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },

  devFab: {
    position: 'absolute',
    right: 18,
    bottom: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  devFabText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  devOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  devRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  devLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },

  debugBox: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bg,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },

  debugOverlayWrap: {
    position: 'absolute',
    right: 12,
    bottom: 18,
  },
  debugOverlayCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    width: 260,
  },
  debugOverlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  debugOverlayHeaderDragArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  debugOverlayHeaderText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  debugOverlayHeaderHint: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  debugOverlayClose: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  debugOverlayCloseText: {
    color: COLORS.muted,
    fontSize: 14,
    fontWeight: '900',
    marginTop: -1,
  },
  debugOverlayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  debugOverlayLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  debugOverlayBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
  },
  debugOverlayBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  debugOverlayBtnWide: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
  },
  debugOverlayBtnWideText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  debugOverlayReopen: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignSelf: 'flex-end',
  },
  debugOverlayReopenText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  filtersGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  filterActions: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  btnSecondary: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  btnSecondaryText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },

  selectWrap: {
    position: 'relative',
  },
  selectBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  selectText: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },
  selectMenu: {
    position: 'absolute',
    top: 44,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    zIndex: 9999,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  selectMenuItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  selectMenuItemFirst: {
    borderTopWidth: 0,
  },
  selectMenuText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },

  selectSearchWrap: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  selectSearchInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  selectMenuScroll: {
    maxHeight: 280,
  },
  selectMenuScrollContent: {
    paddingBottom: 6,
  },
  selectMenuDetailText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  selectMenuEmpty: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  selectMenuFooterBtn: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.bg,
  },
  selectMenuFooterText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },

  dialogOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    padding: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dialogCard: {
    width: '100%',
    maxWidth: 520,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    padding: 14,
  },
  dialogTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 8,
  },
  dialogMessage: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  dialogActionsRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  dialogBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  dialogBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  dialogBtnOk: {
    backgroundColor: COLORS.text,
    borderColor: COLORS.text,
  },
  dialogBtnDanger: {
    backgroundColor: '#ef4444',
    borderColor: '#ef4444',
  },
  dialogBtnOkText: {
    color: COLORS.white,
  },

  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    padding: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerModalCard: {
    width: '100%',
    maxWidth: 560,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    overflow: 'hidden',
  },
  pickerModalHeader: {
    height: 46,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerModalTitle: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
    flex: 1,
  },
  pickerModalClose: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerModalCloseText: {
    color: COLORS.muted,
    fontSize: 16,
    fontWeight: '900',
    marginTop: -1,
  },
  pickerModalList: {
    maxHeight: 420,
  },
  pickerModalListContent: {
    paddingBottom: 6,
  },
  pickerModalItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  pickerModalItemText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  pickerModalDoneBtn: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: COLORS.text,
  },
  pickerModalDoneText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },

  uploadBarOuter: {
    marginTop: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bg,
    overflow: 'hidden',
  },
  uploadBarInner: {
    height: '100%',
    backgroundColor: COLORS.text,
  },

  multiChipsWrap: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  multiChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bg,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: '100%',
    marginRight: 8,
    marginBottom: 8,
  },
  multiChipText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 260,
  },
  multiChipRemove: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
    marginLeft: 8,
  },
  multiSelectRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  multiSelectCheck: {
    width: 18,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 1,
    textAlign: 'center',
  },
  multiSelectTextCol: {
    flex: 1,
  },

  tableScroll: {
    width: '100%',
  },
  videoTable: {
    minWidth: 1180,
  },
  videoRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  videoHeaderRow: {
    backgroundColor: COLORS.bg,
  },
  videoRowDim: {
    opacity: 0.6,
  },
  videoCell: {
    width: 110,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  videoHeaderCell: {
    fontWeight: '900',
  },
  thumb: {
    width: 64,
    height: 36,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    backgroundColor: COLORS.bg,
  },
  actionsCell: {
    width: 240,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  smallBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  smallBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  smallBtnPrimary: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.primary,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  smallBtnPrimaryText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '900',
  },
  tagTemplateRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  tagTemplateButton: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: COLORS.bg,
  },
  tagTemplateButtonActive: {
    borderColor: COLORS.text,
    backgroundColor: COLORS.text,
  },
  tagTemplateText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  tagTemplateTextActive: {
    color: COLORS.white,
  },
  smallBtnDanger: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.danger,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  smallBtnDangerText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '900',
  },
  pagination: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
  },
  pageBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  pageBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  pageInfo: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
  },

  pageJump: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pageInput: {
    width: 64,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  contentScroll: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  contentInner: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    gap: 16,
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
  },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  pageTitle: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
  },
  section: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    backgroundColor: COLORS.white,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },

  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  kpiCard: {
    width: '31%',
    minWidth: 220,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 12,
    backgroundColor: COLORS.white,
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 1,
  },
  kpiLabel: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  kpiValue: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: '900',
  },

  table: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
    minHeight: 52,
  },
  tableLeft: {
    flex: 1,
    gap: 4,
  },
  tableLabel: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },
  tableDetail: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  tableRight: {
    marginLeft: 12,
    alignItems: 'flex-end',
    minWidth: 90,
  },
  pendingText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  pendingTextEmph: {
    color: COLORS.text,
    fontWeight: '900',
  },

  shortcutGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  shortcutCard: {
    width: '31%',
    minWidth: 220,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 1,
  },
  shortcutText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },

  placeholderBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 18,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 160,
  },
  placeholderText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },

  // Login
  loginRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  loginCard: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 18,
    maxWidth: 520,
  },
  loginTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: '900',
  },
  loginDesc: {
    marginTop: 8,
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  banner: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.primarySoft,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bannerText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  form: {
    marginTop: 14,
    gap: 12,
  },
  field: {
    gap: 8,
  },
  label: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
    backgroundColor: COLORS.white,
  },
  readonlyText: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '900',
    color: COLORS.text,
    backgroundColor: COLORS.bg,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 2,
  },
  check: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  checkOn: {
    borderColor: COLORS.text,
  },
  checkBox: {
    width: 14,
    height: 14,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  checkBoxOn: {
    borderColor: COLORS.text,
    backgroundColor: COLORS.text,
  },
  checkText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  linkBtn: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  linkText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  actions: {
    marginTop: 6,
    alignItems: 'flex-end',
  },
  btnPrimary: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  btnPrimaryText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
  },
  btnDisabled: {
    opacity: 0.5,
  },
  footer: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  footerText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
  },
})
