import { Platform, StyleSheet } from 'react-native'

export const COLORS = {
  bg: '#f3f4f6',
  sidebarBg: '#f9fafb',
  text: '#111827',
  muted: '#6b7280',
  placeholder: '#9ca3af',
  border: '#d1d5db',
  white: '#ffffff',
  primary: '#2563eb',
  primarySoft: '#eff6ff',
  danger: '#dc2626',
}

export const LOGIN_COLORS = {
  bg: '#0b0b0b',
  surface: '#111111',
  border: 'rgba(255,255,255,0.38)',
  borderStrong: 'rgba(255,255,255,0.55)',
  text: '#ffffff',
  muted: 'rgba(255,255,255,0.70)',
  muted2: 'rgba(255,255,255,0.55)',
  accent: '#d9a321',
  accentText: '#0b0b0b',
}

// NOTE: This is intentionally exported as a single shared StyleSheet.
// Existing screens rely on these keys.
export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },

  header: {
    height: 56,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? ({ position: 'sticky', top: 0, zIndex: 10 } as any) : null),
  },
  headerLogo: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '900',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 200,
    justifyContent: 'flex-end',
  },
  headerUser: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 280,
  },
  logoutBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  logoutBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  body: {
    flex: 1,
    flexDirection: 'row',
  },

  sidebar: {
    width: 280,
    borderRightWidth: 1,
    borderRightColor: COLORS.border,
    backgroundColor: COLORS.sidebarBg,
  },
  sidebarInner: {
    paddingVertical: 10,
  },
  sidebarGroup: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
  },
  sidebarGroupText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  sidebarItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  sidebarItemActive: {
    backgroundColor: COLORS.primarySoft,
  },
  sidebarItemLabel: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  sidebarItemLabelActive: {
    fontWeight: '900',
    color: COLORS.primary,
  },
  sidebarItemIndent: {
    paddingLeft: 28,
  },

  main: {
    flex: 1,
  },

  devOverlay: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    left: 12,
    top: 12,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  devRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  devLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },

  debugBox: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bg,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },

  debugOverlayWrap: {
    position: 'absolute',
    right: 12,
    bottom: 18,
  },
  debugOverlayCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    width: 260,
  },
  debugOverlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  debugOverlayHeaderDragArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  debugOverlayHeaderText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  debugOverlayHeaderHint: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  debugOverlayClose: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  debugOverlayCloseText: {
    color: COLORS.muted,
    fontSize: 14,
    fontWeight: '900',
    marginTop: -1,
  },
  debugOverlayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  debugOverlayLabel: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
  },
  debugOverlayBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
  },
  debugOverlayBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  debugOverlayBtnWide: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
  },
  debugOverlayBtnWideText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  debugOverlayReopen: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignSelf: 'flex-end',
  },
  debugOverlayReopenText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },

  filtersGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  filterActions: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  btnSecondary: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  btnSecondaryText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
  },

  selectWrap: {
    position: 'relative',
  },
  selectBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  selectText: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '700',
  },

  selectSearchWrap: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  selectSearchInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
  },
  selectMenuDetailText: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  selectMenuEmpty: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },

  dialogOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    padding: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dialogCard: {
    width: '100%',
    maxWidth: 520,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    padding: 14,
  },
  dialogTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 8,
  },
  dialogMessage: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  dialogActionsRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  dialogBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  dialogBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  dialogBtnOk: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  dialogBtnDanger: {
    backgroundColor: COLORS.danger,
    borderColor: COLORS.danger,
  },
  dialogBtnOkText: {
    color: COLORS.white,
  },

  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    padding: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerModalCard: {
    width: '100%',
    maxWidth: 560,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    overflow: 'hidden',
  },
  pickerModalHeader: {
    height: 46,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerModalTitle: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '900',
    flex: 1,
  },
  pickerModalClose: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerModalCloseText: {
    color: COLORS.muted,
    fontSize: 16,
    fontWeight: '900',
    marginTop: -1,
  },
  pickerModalList: {
    maxHeight: 420,
  },
  pickerModalListContent: {
    paddingBottom: 6,
  },
  pickerModalItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  pickerModalItemText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
  },
  pickerModalDoneBtn: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  pickerModalDoneText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },

  multiChipsWrap: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  multiChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.bg,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: '100%',
    marginRight: 8,
    marginBottom: 8,
  },
  multiChipText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 260,
  },
  multiChipRemove: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
    marginLeft: 8,
  },
  multiSelectCheck: {
    width: 18,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 1,
    textAlign: 'center',
  },
  multiSelectTextCol: {
    flex: 1,
  },

  table: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.bg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tableHeaderCell: {
    paddingRight: 10,
  },
  tableHeaderText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.white,
    minHeight: 52,
  },
  tableRowInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tableCellText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  colName: {
    flexGrow: 1.2,
    flexBasis: 0,
    paddingRight: 10,
  },
  colEmail: {
    flexGrow: 1.8,
    flexBasis: 0,
    paddingRight: 10,
  },
  colCreatedAt: {
    flexGrow: 1.0,
    flexBasis: 0,
    paddingRight: 10,
  },
  colSubscribed: {
    flexGrow: 0.9,
    flexBasis: 0,
    paddingRight: 10,
  },
  colPermission: {
    flexGrow: 0.7,
    flexBasis: 0,
    paddingRight: 10,
  },
  colCast: {
    flexGrow: 0.7,
    flexBasis: 0,
  },
  colActions: {
    flexGrow: 1.0,
    flexBasis: 0,
    alignItems: 'flex-end',
  },
  tableDetail: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },

  smallBtn: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  smallBtnText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '900',
  },
  smallBtnPrimary: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: COLORS.primary,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  smallBtnPrimaryText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '900',
  },

  btnPrimary: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    borderWidth: 1,
    borderColor: COLORS.primary,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : null),
  },
  btnPrimaryText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '900',
  },
  btnDisabled: {
    opacity: 0.55,
  },

  placeholderBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 18,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 160,
  },
  placeholderText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
  },

  miniHelpText: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },

  contentScroll: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  contentInner: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    gap: 16,
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
  },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  pageTitle: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
  },
  section: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    backgroundColor: COLORS.white,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: '900',
  },

  banner: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.primarySoft,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bannerText: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  field: {
    gap: 8,
  },
  label: {
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
    backgroundColor: COLORS.white,
  },
  readonlyText: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '900',
    color: COLORS.text,
    backgroundColor: COLORS.bg,
  },

  // Login
  loginRoot: {
    flex: 1,
    backgroundColor: LOGIN_COLORS.bg,
  },
  loginBgGlow: {
    position: 'absolute',
    left: -140,
    top: -120,
    width: 360,
    height: 360,
    borderRadius: 200,
    backgroundColor: LOGIN_COLORS.accent,
    opacity: 0.12,
  },
  loginHeader: {
    height: 64,
    paddingTop: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  loginBackBtn: {
    width: 40,
    height: 40,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  loginBackText: {
    color: LOGIN_COLORS.text,
    fontSize: 28,
    fontWeight: '700',
    marginTop: -2,
  },
  loginHeaderTitle: {
    color: LOGIN_COLORS.text,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  loginHeaderRightSpacer: {
    width: 40,
    height: 40,
  },
  loginContent: {
    flex: 1,
    paddingHorizontal: 22,
    paddingBottom: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLogoWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 34,
  },
  loginLogo: {
    width: 190,
    height: 62,
  },
  loginFields: {
    width: '100%',
    maxWidth: 420,
    gap: 14,
  },
  loginBanner: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  loginBannerText: {
    color: LOGIN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  loginInput: {
    height: 54,
    borderWidth: 1,
    borderColor: LOGIN_COLORS.border,
    borderRadius: 6,
    paddingHorizontal: 16,
    fontSize: 14,
    fontWeight: '700',
    color: LOGIN_COLORS.text,
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  loginPrimaryBtn: {
    marginTop: 6,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LOGIN_COLORS.accent,
    shadowColor: LOGIN_COLORS.accent,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  loginPrimaryText: {
    color: LOGIN_COLORS.accentText,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  loginBtnDisabled: {
    opacity: 0.55,
  },
  loginHelpBtn: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  loginHelpText: {
    color: LOGIN_COLORS.muted,
    fontSize: 12,
    fontWeight: '700',
  },
})
